### ISSUE TITLE
What's the best way to cache resource responses?

### ISSUE THREAD

**Issue by duprasa** [graphiti-api/graphiti#160]
Hi congrats on writing this great library.

I'm considering using graphiti for our application, but before committing to migrating our codebase I wanted to know what strategy we should use to cache resources/responses (all I could find on the website was about Etags).

We have a few models on the site that take a while to compute/render, but the same query is requested often, but updated infrequently. 

What we have done previously is wrap the response in a cache block and test to see if anything has updated, something like this:

```
max_updated_at = Products.where(params).pluck('MAX(updated_at)').first
data = cache("Products:#{max_updated_at}") do
  Products.where(params).map { |p| p.as_api_hash }
end
render json: { data: data}, status: 200
```

Here we can just do a small initial test query to generate a cache key, and if it doesn't change we can just re-use the previous returned data instead of recomputing/calculating it.

How could I do something similar with graphiti?

Is there other built in caching mechanisms?

Thanks a lot and keep up the good work!

**Comment by richmolj** [comment]
Hey @sam-dupras thanks for your kind words ❤️ !

I personally do this with [action caching](https://github.com/rails/actionpack-action_caching) the JSON response, which makes this more a Rails concern than a Graphiti one. This is good because you can cache the query itself and the serialization, and often these caches work best per-endpoint rather than per-Resource. You can tune the hash based on the query params, or like you're doing above with max updated at.

But you could also build something similar to your example above within your Resource:

```ruby
# pseudo-code
def before_resolve(scope, query)
  # Create a hash from the query params
  # Or something similar to your max updated at would be possible
  cache_key = Digest::MD5.hexdigest(query.hash.to_json)
  # Store the raw attributes in the cache
  record_attributes = Rails.cache.fetch(cache_key) do
    records = super
    records.map(&:attributes)
  end
  # return model instances
  record_attributes.map { |attrs| Product.new(attrs) }
end
```

Which would cache the query, but not the serialization.

There's nothing built directly into Graphiti for this, but as you can see a few different ways to go about the same. I recommend action caching, possibly creating a specific endpoint just for this.
