### ISSUE TITLE
Does Graphiti support custom actions other than create/show/index/update/delete?

### ISSUE THREAD

**Issue by yjukaku** [graphiti-api/graphiti#179]
Hello, thanks for your work on this project! I'm really liking Graphiti so far, but I do have a question.

I'm looking at how it could be possible to migrate an existing API to Graphiti. One of the issues I've run into is that we currently have a few "non-standard" actions in our existing API.  For example, in our client, we have the ability for users to navigate through a group of items. If they use our mobile app, they should be able to start navigating at the same point in the group where they left off at. To that end, our existing API has an endpoint `/api/v1/items/current` which corresponds to `ItemsController#current`.

Are these kind of custom actions supported by Graphiti? What are the pros and cons of using such an approach as far as Graphiti's tools go?

**Comment by yjukaku** [comment]
I did find the [User Account app](https://github.com/graphiti-api/user-account-app-cookbook) which has a `/api/v1/users/current` endpoint, but I'm unsure is this "officially" supported by Graphiti's standards.

**Comment by richmolj** [comment]
Hey @yjukaku! We don't support non-RESTful actions (or at least, don't encourage them). That said, I think the UserAccount approach - in which you have a `show` action with a special identifier - is totally fine. You're absolutely passing a resource identifier, it just doesn't happen to correspond to a database id.

**Comment by caseyprovost** [comment]
@yjukaku If you are wondering how to structure non-restful requests, here are some examples of how I tend to think about it.

Let's say you want to have this endpoint: `PATCH /orders/1/cancel`. The problem is that it doesn't play nice with REST-ful architecture right? Instead, try something like `POST /order_cancellations`. 

A more complex example:
In a recent application, we needed the ability to clone objects. We really wanted `POST /orders/1/clone` to work, but it wasn't RESTful so some of our automated toolings didn't work as well. The first instinct might be to create a `POST /order_clones` endpoint...but then you have all of these extract objects, resources, etc, etc. In this case, I would (and did) something more pragmatic `POST /orders` but in the payload pass a `clone_from` or similar parameter with the source order as the value of that. This allows you to stay in the RESTful world while still accomplishing those more "odd" types of requests.

**Comment by yjukaku** [comment]
@caseyprovost , thanks for the examples. What would you `respond_with` for an `order_cancellation`, though? A `Graphiti::Resource` doesn't seem to make much sense for that... 🤔

**Comment by caseyprovost** [comment]
@yjukaku i totally would respond with a Graphiti resource that is not ActiveRecord back :) I’d have it maybe respond with a success flag and order relationship.
