### ISSUE TITLE
Any examples of using this with devise_token_auth?

### ISSUE THREAD

**Issue by jfrux** [graphiti-api/graphiti#19]
I'm getting an error of:
```
Processing by DeviseTokenAuth::RegistrationsController#create as */*
  Parameters: {"email"=>"test2@test.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "confirm_success_url"=>"http://localhost:3000"}
ERROR: NoMethodError: undefined method `new' for nil:NilClass
```

But only when I use this gem...?

Any tips?

**Comment by richmolj** [comment]
Hi @joshuairl - it looks like you are not sending a JSONAPI payload to `RegistrationsController#create`, so the suite isn't going to work. That's OK though - just make sure your JSONAPI controllers inherit from something like `JSONAPIApplicationController` and your vanilla controllers inherit from normal `ApplicationController`. The suite will get out of your way.

**Comment by joshuairl** [comment]
Thanks so much for quick response!!

Ideally I’d like JSONAPI compliant responses for my Auth controller.

Will I need to override the devise token auth controllers in my app and
implement something from JSONAPI suite?

**Comment by richmolj** [comment]
Are you saying you want the request to not be JSONAPI compliant, but the response should be? In this case I would just manually format the json since this is a one-off.

Otherwise, I would try to treat this like any other JSONAPI Resource - we're POSTing an Authentication object the same way we'd POST an Employee object. This probably involves hooking in to devise's lower-level methods.

Also feel free to email richmolj@gmail.com to join a slack chat where we discuss questions like this.
