### ISSUE TITLE
Transform keys to camelLower

### ISSUE THREAD

**Issue by andychongyz** [graphiti-api/graphiti#195]
Hi, is there any support or ways to transform the keys from snake_case to camelLower. If not, then is there any way to integrate fast_jsonapi serializer with graphiti resource?

https://github.com/Netflix/fast_jsonapi#key-transforms

**Comment by richmolj** [comment]
We use jsonapi-rb under the hood, and you can change key casing with it (see [this issue](https://github.com/graphiti-api/graphiti/issues/7)). That issue is a bit old but doing the same with `Graphiti::Serializer` or `ApplicationResource.serializer` should work.

That said, this will only change the casing of the response json - the URL doesn't change. Functionality like that is currently unsupported.

You could also do all this with before/after filters.

**Comment by chozandrias76** [comment]
I think this method is potentially outdated. Can you advise on the new method?

I tried 
```rb
class ApplicationResource < Graphiti::Resource
  extend JSONAPI::Serializable::Resource::KeyFormat
  self.adapter = Graphiti::Adapters::ActiveRecord
  self.attributes_writable_by_default = false
  self.endpoint_namespace = "/api/v1"
  self.abstract_class = true
  self.validate_endpoints = false
  key_format -> (key) { key.to_s.camelize(:lower) }
end
```
```rb
ResourceResource.all({filter: {other_id: 12}})
/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/graphiti-1.2.32/lib/graphiti/resource/dsl.rb:66:in `sort': Tried to add sort-only attribute "email", but type was missing! (Graphiti::Errors::ImplicitSortTypeMissing)

If you are adding a sort that does not have a corresponding attribute, you must pass a type:

sort :name, :string do <--- like this
  # ... code ...
end
```

**Comment by richmolj** [comment]
Hm, looks like your snippet does not match the linked solution
